### ISSUE TITLE
Adpater stürzt ab

### ISSUE THREAD

**Issue by Cosmicbase** [ioBroker/ioBroker.echarts#120]
Adapter stürzt ab sobald ein Bild gesendet wird.

echarts.0
2022-07-28 08:07:31.058	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

echarts.0
2022-07-28 08:07:31.056	info	terminating

echarts.0
2022-07-28 08:07:30.547	error	Cannot read properties of undefined (reading 'length')

echarts.0
2022-07-28 08:07:30.546	error	TypeError: Cannot read properties of undefined (reading 'length') at normalizeConfig (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:201:19) at ChartModel.analyseAndLoadConfig (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:288:31) at /opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:279:29

echarts.0
2022-07-28 08:07:30.545	error	unhandled promise rejection: Cannot read properties of undefined (reading 'length')

echarts.0
2022-07-28 08:07:30.543	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

echarts.0
2022-07-28 08:07:14.570	info	starting. Version 1.0.12 in /opt/iobroker/node_modules/iobroker.echarts, node: v16.16.0, js-controller: 4.0.23

echarts.0
2022-07-28 08:06:40.980	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

echarts.0
2022-07-28 08:06:40.977	info	terminating

echarts.0
2022-07-28 08:06:40.468	error	Cannot read properties of undefined (reading 'length')

echarts.0
2022-07-28 08:06:40.467	error	TypeError: Cannot read properties of undefined (reading 'length') at normalizeConfig (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:201:19) at ChartModel.analyseAndLoadConfig (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:288:31) at /opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:279:29

echarts.0
2022-07-28 08:06:40.465	error	unhandled promise rejection: Cannot read properties of undefined (reading 'length')

echarts.0
2022-07-28 08:06:40.459	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

echarts.0
2022-07-28 08:05:45.371	info	starting. Version 1.0.12 in /opt/iobroker/node_modules/iobroker.echarts, node: v16.16.0, js-controller: 4.0.23

echarts.0
2022-07-28 08:05:11.918	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

echarts.0
2022-07-28 08:05:11.916	info	terminating

echarts.0
2022-07-28 08:05:11.407	error	Cannot read properties of undefined (reading 'length')

echarts.0
2022-07-28 08:05:11.406	error	TypeError: Cannot read properties of undefined (reading 'length') at normalizeConfig (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:201:19) at ChartModel.analyseAndLoadConfig (/opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:288:31) at /opt/iobroker/node_modules/iobroker.echarts/_helpers/ChartModel.js:279:29

echarts.0
2022-07-28 08:05:11.405	error	unhandled promise rejection: Cannot read properties of undefined (reading 'length')

echarts.0
2022-07-28 08:05:11.399	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

echarts.0
2022-07-28 07:35:09.414	info	starting. Version 1.0.12 in /opt/iobroker/node_modules/iobroker.echarts, node: v16.16.0, js-controller: 4.0.23

**Comment by Apollon77** [comment]
Please try if it happens again in current versions

**Comment by GermanBluefox** [comment]
i cannot reproduce it
