### ISSUE TITLE
Version 1.9.5 does not work

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.echarts#758]
Adapter is "red"
Log:
`<html><body>

host.iobroker | 2024-12-20 17:28:47.634 | error | instance system.adapter.echarts.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2024-12-20 17:28:47.634 | error | Caught by controller[1]: Node.js v20.18.1
host.iobroker | 2024-12-20 17:28:47.634 | error | Caught by controller[0]: }
host.iobroker | 2024-12-20 17:28:47.634 | error | Caught by controller[0]:   path: '/opt/iobroker/node_modules/iobroker.echarts/src/src-chart/src/Components/ChartModel.js'
host.iobroker | 2024-12-20 17:28:47.634 | error | Caught by controller[0]:   syscall: 'open',
host.iobroker | 2024-12-20 17:28:47.634 | error | Caught by controller[0]:   code: 'ENOENT',
host.iobroker | 2024-12-20 17:28:47.634 | error | Caught by controller[0]:   errno: -2,
host.iobroker | 2024-12-20 17:28:47.634 | error | Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1288:32) {
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught  by controller[0]:     at Object.newLoader [as .ts]  (/opt/iobroker/node_modules/@alcalzone/esbuild-register/dist/node.js:2318:11)
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:     at extensions..js (/opt/iobroker/node_modules/@alcalzone/esbuild-register/dist/node.js:2755:24)
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:     at Module._compile (/opt/iobroker/node_modules/@alcalzone/esbuild-register/dist/node.js:2314:28)
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1469:14)
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.echarts/src/main.ts:15:1)
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:     at prepareReactFiles (/opt/iobroker/node_modules/iobroker.echarts/src/main.ts:40:26)
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:     at Object.readFileSync (node:fs:452:35)
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:     at Object.openSync (node:fs:573:18)
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught  by controller[0]: Error: ENOENT: no such file or directory, open  '/opt/iobroker/node_modules/iobroker.echarts/src/src-chart/src/Components/ChartModel.js'
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:         ^
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]:         throw error;
host.iobroker | 2024-12-20 17:28:47.633 | error | Caught by controller[0]: /opt/iobroker/node_modules/@alcalzone/esbuild-register/dist/node.js:2758
host.iobroker | 2024-12-20 17:28:46.608 | info | instance system.adapter.echarts.0 in version "1.9.5" started with pid 392915

</body>
</html>

iobroker in a proxmox debian container, node.js 20.18.1, js-controller 7.0.6.
I changed back to v1.9.2, works fine`

**Comment by harvey637** [comment]
Same here, revert back to 1.9.2. is working

(bye the way, this function is great, if it will work!)

**Comment by Nunmalfix** [comment]
Same here, seems that path to ChartModel.js is wrong

node_modules/iobroker.echarts/src/src-chart/src/Components/ChartModel.js
 
two times src isn't correct - ChartModel.js is here 

node_modules/iobroker.echarts/src-chart/src/Components/

**Comment by Castellanus** [comment]
Same here, back to 1.9.2

**Comment by SurfGargano** [comment]
Me too.

**Comment by AndiT61** [comment]
What is the command to revert back to version 1.9.2 of echarts? Thanks for your hints

**Comment by xMFPx** [comment]
same Problem here ... 1.9.2 is working


> What is the command to revert back to version 1.9.2 of echarts? Thanks for your hints

At the iobroker page change to expert mode, then you can choose the version at the Adapter screen.

**Comment by AndiT61** [comment]
> same Problem here ... 1.9.2 is working
> 
> > What is the command to revert back to version 1.9.2 of echarts? Thanks for your hints
> 
> At the iobroker page change to expert mode, then you can choose the version at the Adapter screen.

thank you very much for this hint, it works

**Comment by itProfi** [comment]
same problem
```
<html>
<body>
<!--StartFragment-->
2024-12-28 16:39:21.505 | info | Restart adapter system.adapter.echarts.0 because enabled
-- | -- | --
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | instance system.adapter.echarts.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: Node.js v20.18.1
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: }
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: path: '/opt/iobroker/node_modules/iobroker.echarts/src/src-chart/src/Components/ChartModel.js'
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: syscall: 'open',
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: code: 'ENOENT',
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: errno: -2,
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1288:32) {
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: at Object.newLoader [as .ts] (/opt/iobroker/node_modules/@alcalzone/esbuild-register/dist/node.js:2318:11)
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: at extensions..js (/opt/iobroker/node_modules/@alcalzone/esbuild-register/dist/node.js:2755:24)
host.iobroker-x64 | 2024-12-28 16:39:21.505 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: at Module._compile (/opt/iobroker/node_modules/@alcalzone/esbuild-register/dist/node.js:2314:28)
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1469:14)
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.echarts/src/main.ts:15:1)
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: at prepareReactFiles (/opt/iobroker/node_modules/iobroker.echarts/src/main.ts:40:26)
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: at Object.readFileSync (node:fs:452:35)
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: at Object.openSync (node:fs:573:18)
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.echarts/src/src-chart/src/Components/ChartModel.js'
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: ^
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: throw error;
host.iobroker-x64 | 2024-12-28 16:39:21.504 | error | Caught by controller[0]: /opt/iobroker/node_modules/@alcalzone/esbuild-register/dist/node.js:2758

<!--EndFragment-->
</body>
</html>
```

**Comment by Berniiiii** [comment]
Hallo,
bei mir das gleiche.
Gutes neues Jahr Wünsche ich.
Gruß berniiii

**Comment by amg666** [comment]
New version 2.0.0 works fine, thx :-)
